AWSTemplateFormatVersion: "2010-09-09"
Description:  >
  Creates a stack containing an IAM Role for reading CCFT data.

  Belongs to the SAM template to automate the monthly extraction of new CCFT data within a multi account structure (uksb-880c16twdr).
Parameters:
  CCFTReadDataRole:
    Type: String
    Default: ccft-read-role
    Description: Role for reading CCFT data
  ManagementAccount:
    Description: Management Account ID number
    Type: String
Resources:

  CCFTReadAccountDataPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      ManagedPolicyName: !Ref CCFTReadDataRole
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - 'sustainability:GetCarbonFootprintSummary'
            Resource: "*"

  CCFTReadAccountDataRole:
    Type: 'AWS::IAM::Role'
    Metadata:
      guard:
        SuppressedRules:
          # we don't need to reuse the policy in other roles and inline it
          - IAM_NO_INLINE_POLICY_CHECK
    Properties:
      RoleName:
        !Ref CCFTReadDataRole
      Path: /
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Sub 'arn:aws:iam::${ManagementAccount}:root'
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: CCFT-Read-Data-Policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: CCFTReadData
                Effect: Allow
                Resource: "*"
                Action:
                  - 'sustainability:GetCarbonFootprintSummary'